"""
語言字典檔
所有介面上的文字都儲存在這裡，實現程式邏輯與顯示文字的分離。
"""

LANGUAGES = {
    "zh_tw": {
        "window_title": "檔案自動分類工具 V2.1",
        "profile_frame_title": "E. 設定檔管理",
        "load_profile_btn": "載入",
        "save_profile_btn": "儲存",
        "save_as_profile_btn": "另存新檔...",
        "delete_profile_btn": "刪除",
        "new_profile_prompt_title": "新設定檔",
        "new_profile_prompt_msg": "請輸入新設定檔的名稱:",
        "profile_load_success": "已成功載入設定檔: {}",
        "profile_save_success": "已成功儲存設定檔: {}",
        "profile_delete_confirm": "確定要刪除設定檔 '{}' 嗎？",
        "source_frame_title": "A. 來源資料夾設定",
        "add_source_btn": "新增來源",
        "batch_add_source_btn": "批次新增",
        "remove_source_btn": "移除所選",
        "remove_all_sources_btn": "全部移除",
        "batch_add_prompt_title": "批次新增來源",
        "batch_add_prompt_msg": "請貼上資料夾路徑 (一行一個):",
        "recursive_checkbtn": "包含子資料夾中的檔案 (遞迴掃描)",
        "rules_frame_title": "B. 分類規則設定",
        "col_enabled": "啟用",
        "col_name": "規則名稱",
        "col_keyword": "檔名包含",
        "col_date_filter": "日期篩選條件",
        "col_destination": "目標資料夾",
        "add_rule_btn": "新增規則",
        "edit_rule_btn": "編輯所選",
        "copy_rule_btn": "複製所選",
        "delete_rule_btn": "刪除所選",
        "conflict_frame_title": "C. 符合多條規則的檔案存放至",
        "browse_btn": "瀏覽...",
        "action_frame_title": "D. 執行與狀態",
        "start_button": "開始分類檔案",
        "log_frame_title": "狀態日誌",
        "lang_button": "Switch to English",
        "confirm_delete_title": "確認",
        "confirm_delete_msg": "確定要刪除所選的規則嗎？",
        "info_title": "提示",
        "select_rule_to_edit_msg": "請先選擇一條要編輯的規則。",
        "select_rule_to_copy_msg": "請先選擇一條要複製的規則。",
        "select_rule_to_delete_msg": "請先選擇一條要刪除的規則。",
        "error_title": "錯誤",
        "config_validation_error": "請檢查來源、啟用規則和衝突資料夾設定是否正確。",
        "config_save_warning_title": "警告",
        "config_save_warning_msg": "無法儲存設定檔: {}",
        "config_load_error_msg": "無法讀取設定檔: {}",
        "log_start_task": "=== 開始分類任務 @ {} ===",
        "log_scanning": "掃描: {}...",
        "log_read_error": "錯誤: 無法讀取 {}: {}",
        "log_task_complete": "=== 任務完成 @ {} ===",
        "log_summary": "成功分類 {} 個檔案，衝突 {} 個。",
        "log_duration": "總耗時: {:.2f} 秒。",
        "log_copied": "  -> '{}' 符合 '{}'",
        "log_copy_failed": "  !! 複製失敗: '{}', 原因: {}",
        "log_conflict": "  !! '{}' 衝突 ({})",
        "log_conflict_failed": "  !! 移至衝突資料夾失敗: '{}', 原因: {}",
        "date_display_none": "無",
        "rule_editor_add_title": "新增規則",
        "rule_editor_edit_title": "編輯規則",
        "rule_name_label": "規則名稱:",
        "keyword_label": "檔名包含:",
        "date_filter_label": "日期篩選:",
        "dest_folder_label": "目標資料夾:",
        "date_options": ["不篩選日期", "修改日期晚於", "修改日期早於", "修改日期介於"],
        "date_label": "日期 (YYYY-MM-DD):",
        "date_from_label": "從:",
        "date_to_label": "到",
        "save_btn": "儲存",
        "cancel_btn": "取消",
        "ok_btn": "確定",
        "rule_editor_error_name_dest_empty": "「規則名稱」和「目標資料夾」不可為空！",
        "rule_editor_error_date_empty": "請填寫日期！",
        "rule_editor_error_date_format": "日期格式不正確，請使用 YYYY-MM-DD。",
        "rule_editor_error_start_end_date_empty": "請填寫開始和結束日期！",
        "rule_editor_error_date_order": "開始日期不能晚於結束日期。",
        "copied_suffix": " (複製)",
    },
    "en": {
        "window_title": "File Classifier V2.1",
        "profile_frame_title": "E. Profile Management",
        "load_profile_btn": "Load",
        "save_profile_btn": "Save",
        "save_as_profile_btn": "Save As...",
        "delete_profile_btn": "Delete",
        "new_profile_prompt_title": "New Profile",
        "new_profile_prompt_msg": "Please enter a name for the new profile:",
        "profile_load_success": "Successfully loaded profile: {}",
        "profile_save_success": "Successfully saved profile: {}",
        "profile_delete_confirm": "Are you sure you want to delete the profile '{}'?",
        "source_frame_title": "A. Source Folders",
        "add_source_btn": "Add Source",
        "batch_add_source_btn": "Batch Add",
        "remove_source_btn": "Remove Selected",
        "remove_all_sources_btn": "Remove All",
        "batch_add_prompt_title": "Batch Add Sources",
        "batch_add_prompt_msg": "Paste folder paths (one per line):",
        "recursive_checkbtn": "Include files in sub-folders (Recursive Scan)",
        "rules_frame_title": "B. Classification Rules",
        "col_enabled": "Enabled",
        "col_name": "Rule Name",
        "col_keyword": "Filename Contains",
        "col_date_filter": "Date Filter",
        "col_destination": "Destination Folder",
        "add_rule_btn": "Add Rule",
        "edit_rule_btn": "Edit Selected",
        "copy_rule_btn": "Copy Selected",
        "delete_rule_btn": "Delete Selected",
        "conflict_frame_title": "C. Destination for Files Matching Multiple Rules",
        "browse_btn": "Browse...",
        "action_frame_title": "D. Execution & Status",
        "start_button": "Start Classification",
        "log_frame_title": "Status Log",
        "lang_button": "切換為繁體中文",
        "confirm_delete_title": "Confirm",
        "confirm_delete_msg": "Are you sure you want to delete the selected rule?",
        "info_title": "Info",
        "select_rule_to_edit_msg": "Please select a rule to edit.",
        "select_rule_to_copy_msg": "Please select a rule to copy.",
        "select_rule_to_delete_msg": "Please select a rule to delete.",
        "error_title": "Error",
        "config_validation_error": "Please check settings for sources, enabled rules, and conflict folder.",
        "config_save_warning_title": "Warning",
        "config_save_warning_msg": "Could not save config file: {}",
        "config_load_error_msg": "Could not load config file: {}",
        "log_start_task": "=== Starting Classification Task @ {} ===",
        "log_scanning": "Scanning: {}...",
        "log_read_error": "Error: Cannot read folder {}: {}",
        "log_task_complete": "=== Task Finished @ {} ===",
        "log_summary": "Successfully classified {} files, with {} conflicts.",
        "log_duration": "Total time elapsed: {:.2f} seconds.",
        "log_copied": "  -> '{}' matches rule '{}'",
        "log_copy_failed": "  !! Copy failed: '{}', Reason: {}",
        "log_conflict": "  !! '{}' has conflicts ({})",
        "log_conflict_failed": "  !! Move to conflict folder failed: '{}', Reason: {}",
        "date_display_none": "None",
        "rule_editor_add_title": "Add New Rule",
        "rule_editor_edit_title": "Edit Rule",
        "rule_name_label": "Rule Name:",
        "keyword_label": "Filename Contains:",
        "date_filter_label": "Date Filter:",
        "dest_folder_label": "Destination Folder:",
        "date_options": ["No Date Filter", "Modified After", "Modified Before", "Modified Between"],
        "date_label": "Date (YYYY-MM-DD):",
        "date_from_label": "From:",
        "date_to_label": "To",
        "save_btn": "Save",
        "cancel_btn": "Cancel",
        "ok_btn": "OK",
        "rule_editor_error_name_dest_empty": "'Rule Name' and 'Destination Folder' cannot be empty!",
        "rule_editor_error_date_empty": "Please enter a date!",
        "rule_editor_error_date_format": "Incorrect date format. Please use YYYY-MM-DD.",
        "rule_editor_error_start_end_date_empty": "Please enter both start and end dates!",
        "rule_editor_error_date_order": "Start date cannot be after end date.",
        "copied_suffix": " (Copy)",
    }
}